title: "My Personal Website"
description: "Welcome to my GitHub Pages site!"
theme: jekyll-theme-minimal

# Navigation links
nav:
  - name: "Home"
    link: /
  - name: "About Me"
    link: /about
  - name: "Research"
    link: /research
  - name: "Outreach"
    link: /outreach
